# This file was generated by GoReleaser. DO NOT EDIT.
cask "pomo" do
  name "pomo"
  desc "A simple Pomodoro timer TUI application written in Go."
  homepage "https://github.com/Bahaaio/pomo"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pomo"

  on_macos do
    on_intel do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Darwin_x86_64.tar.gz"
      sha256 "eed12ea0148bf12ae3e4818ebed3b99a593eed4e3fcab48c65adf158cd0eebe4"
    end
    on_arm do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Darwin_arm64.tar.gz"
      sha256 "27dfb4fb86acd9190d6ac9ee752521f5bd837560658235b8731904a222f47b32"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Linux_x86_64.tar.gz"
      sha256 "b9c0e948a9c92ca880e6a5ff86f3fa97c7774dc46992334615bba64158e39734"
    end
    on_arm do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Linux_arm64.tar.gz"
      sha256 "96c7d70a5a3538c5d4f3ade9aba79d3a04023a2d368faa608b064a8a57960bf8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pomo"]
    end
  end

  # No zap stanza required
end
