# This file was generated by GoReleaser. DO NOT EDIT.
cask "pomo" do
  name "pomo"
  desc "A simple Pomodoro timer TUI application written in Go."
  homepage "https://github.com/Bahaaio/pomo"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pomo"

  on_macos do
    on_intel do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Darwin_x86_64.tar.gz"
      sha256 "849c4c50ebaf17a86db092ea9683a1b4b9806fc0dcbaa694dd79bc60548fcb74"
    end
    on_arm do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Darwin_arm64.tar.gz"
      sha256 "8b079e9dcac61432aafeb351048a395ab27e00d4cb171249776c42566f6674be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Linux_x86_64.tar.gz"
      sha256 "e840b6ed3242cc95d64dd7dab8ee7ae04d27223604047ca28483958e7134d500"
    end
    on_arm do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Linux_arm64.tar.gz"
      sha256 "ea30e78de79d1eeb85006ac4966b90006ecfc57754fe1fab85358907ae1476ef"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pomo"]
    end
  end

  # No zap stanza required
end
