# This file was generated by GoReleaser. DO NOT EDIT.
cask "pomo" do
  name "pomo"
  desc "A simple Pomodoro timer TUI application written in Go."
  homepage "https://github.com/Bahaaio/pomo"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pomo"

  on_macos do
    on_intel do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Darwin_x86_64.tar.gz"
      sha256 "67b66171181f3b8d986d30a70acd0d9b0f96ee389f488fbeee9ec1ee686b1ede"
    end
    on_arm do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Darwin_arm64.tar.gz"
      sha256 "459771507e93fffcfc7f25ff1cbe96c0a3973649a624de8fa9a0c61b6b3f206c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Linux_x86_64.tar.gz"
      sha256 "32bbde4398bc80b55169d85e9f26ae544bb593055f6fbdd9ced1d93cb17da7c6"
    end
    on_arm do
      url "https://github.com/Bahaaio/pomo/releases/download/v#{version}/pomo_Linux_arm64.tar.gz"
      sha256 "49bea4b62647d5a7b8317dbc88219e858ca0a695ac2b4e5380521a9bc369fd96"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pomo"]
    end
  end

  # No zap stanza required
end
